# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab1427cd84b4258d8ab15600eb0dba0255042879469a9058211578fbcccafb7808608ed9a21731c9b8e8607829ecafe476f2d84966a742e7f734b5a25999507b

test:
  secret_key_base: a895e4a68bbdb7acc6a179f72c25f5b58b902d2d676027ce31ab016e2c4c046b8623687d848fa910beee412c7e578cdb0c0e91e620b3076b96abf6a961f43eaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
